mappings:
  SpellProvider: SilverStripe\SpellCheck\Data\SpellProvider
  SpellController: SilverStripe\SpellCheck\Handling\SpellController
  SpellException: SilverStripe\SpellCheck\Handling\SpellException
  SpellRequestFilter: SilverStripe\SpellCheck\Handling\SpellRequestFilter
  HunSpellProvider: SilverStripe\SpellCheck\Providers\HunSpellProvider
  HunSpellProviderTest: SilverStripe\SpellCheck\Tests\HunSpellProviderTest
  SpellControllerTest: SilverStripe\SpellCheck\Tests\SpellControllerTest
