---
Name: spellcheckroutes
---
Director:
  rules:
    'spellcheck': 'SpellController'
---
Name: spellcheckprovider
---
# Set the default provider to HunSpell
Injector:
  SpellProvider: HunSpellProvider
---
Name: spellcheckprocessors
---
LeftAndMain:
  extensions:
    SpellCheckAdminExtension: SpellCheckAdminExtension
