---
Name: spellcheckroutes
---
Director:
  rules:
    'spellcheck': 'SpellController'
---
Name: spellcheckprovider
---
# Set the default provider to HunSpell
Injector:
  SpellProvider: HunSpellProvider
---
Name: spellcheckprocessors
---
Injector:
  RequestProcessor:
    properties:
      filters:
        - '%$SpellRequestFilter'
